/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "API": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Config": {
      "PERMANENT_STAGE": boolean
      "VITE_CLERK_PUBLISHABLE_KEY": string
      "type": "sst.sst.Linkable"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "SlackClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
