/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ClerkPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Config": {
      "DOMAIN": string
      "PERMANENT_STAGE": boolean
      "VITE_CLERK_PUBLISHABLE_KEY": string
      "type": "sst.sst.Linkable"
    }
    "OpenaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
