/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_CLERK_PUBLISHABLE_KEY: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}